### ISSUE TITLE
Front End

### ISSUE THREAD

**Issue by mohannadhanafi** [FACG5/am-w5-project#2]
#1 
- [ ] index.html
   - [ ] text input
   - [ ] search button
 - [ ] Javascript Files
    - [ ] Make DOM functions
    - [ ] Make fetch function
    - [ ] event listeners
 - [ ] style.css
    - [ ] make the style
