### ISSUE TITLE
Back End

### ISSUE THREAD

**Issue by mohannadhanafi** [FACG5/am-w5-project#3]
#1 
- [ ] server.js
   - [ ] make the server
 - [ ] router.js
    - [ ] Home page
    - [ ] Handle error page
    - [ ] serve Static files
    - [ ] serve API
 - [ ] functions.js
 - [ ] Back-end Test
